name: Black code style check

on:
- push
- pull_request

jobs:
  black:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install black
    - name: Check code style with Black 
      run: |
        black --check --diff .
