name: CI

on:
- push
- pull_request

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install GRASS GIS and other dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc wget
    - name: Get versions of GRASS GIS and Python
      run: |
        grass --version
        # python3 is what is baked into GRASS GIS by default.
        python3 --version
    - name: Install the module
      run: |
        grass --tmp-location XY --exec g.extension extension=${{ github.event.repository.name }} url=. --verbose
    - name: Cache data for testing
      id: cache-data
      uses: actions/cache@v2
      with:
        path: nc_basic_spm_grass7
        key: ${{ runner.os }}-nc_basic_spm_grass7
    - name: Get sample data for testing (NC SPM sample location)
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: |
        grass --tmp-location XY --exec g.extension g.download.location --verbose
        grass --tmp-location XY --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_basic_spm_grass7.tar.gz dbase=~ --verbose
    - name: Run test (manually specified files)
      run: |
        cd testsuite/
        grass -c ~/nc_basic_spm_grass7/test --exec ./test_v_out_keplergl.py
        rm -rf ~/nc_basic_spm_grass7/test
