name: Code quality check

on:
- push
- pull_request

jobs:
  lint:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    - name: Lint with Flake8
      run: |
        flake8 --ignore=E265,F821,E501,W503,E203 --max-line-length=88 --count --statistics --show-source .
    - name: Lint with Pylint
      run: |
        pylint --disable=R,bad-continuation,fixme,import-error --additional-builtins=_ --reports=n --score=n -j0 ${{ github.event.repository.name }}.py
